# About the Authors {.unnumbered}

Bruno Nicenboim (<https://bruno.nicenboim.me>) is an assistant professor in the department of Cognitive Science and AI at Tilburg University, the Netherlands, where he is the principal investigator (PI) of the Computational Psycholinguistics research line. He started studying Electronic Engineering at the National University of Rosario, Argentina, then transitioned to Human Sciences and spent eight years in Israel, where he completed a Bachelor's degree in Sociology and Linguistics and a Master's degree in Linguistics at Tel Aviv University. During this time, he also worked in several IT companies. He then moved to Germany, where he completed a PhD in Cognitive Science at the University of Potsdam and worked for two years as a postdoctoral researcher. His research interests include Bayesian methods, computational cognitive modeling, sentence comprehension, memory processes, decision making, and predictive processing. He regularly teaches short courses on Bayesian data analysis at workshops and summer schools, and he teaches Bayesian modeling and statistics courses in the master's programs Cognitive Science & AI and Data Science and Society at Tilburg University.

Daniel J. Schad (<https://danielschad.github.io/>) is professor of Quantitative Methods in the Psychology department at the HMU Health and Medical University, at Potsdam, Germany. He studied Psychology at the University of Potsdam, Germany, and at the University of Michigan, Ann Arbor, USA. He did a PhD in Cognitive and Mathematical Psychology at the University of Potsdam, working on computational models of eye-movement control and on mindless reading. He then did a five-year post-doc in the field of Computational Psychiatry at the Charité - Universitätsmedizin Berlin, Germany (partly also at the University of Potsdam), with research visits at the ETH Zürich, Switzerland, and the University College London, UK, working on model-free and model-based decision-making and Pavlovian-instrumental transfer in alcohol dependence, and on the cognitive and brain mechanisms underlying Pavlovian conditioning. He has worked as a postdoctoral researcher at the University of Potsdam, conducting research on quantitative methods in Cognitive Science, including contrasts, properties of significance tests, Bayesian Workflow, and Bayes factor analyses, and has been assistant professor at the department of Cognitive Science and AI at Tilburg University.

Shravan Vasishth (<http://vasishth.github.io>) is professor of Psycholinguistics at the University of Potsdam, Germany. He holds the  chair for Psycholinguistics and Neurolinguistics (Language Processing). After completing his Bachelors degree in Japanese from Jawaharlal Nehru University, New Delhi, India,  he spent a total of five years in Osaka, Japan, where he studied Japanese at the Osaka University of Foreign Studies, conducted research at Osaka University, and worked as an in-house translator in a patent law firm in Osaka. He completed an MS in Computer and Information Science (2000-2002) and a PhD in Linguistics (1997-2002) from the Ohio State University, Columbus, USA, and an MSc in Statistics (2011-2015) from the School of Mathematics and Statistics, University of Sheffield, UK. He is a chartered statistician (the Royal Statistical Society, UK; id 128307). He is on the editorial board of the open access journal Glossa: Psycholinguistics. His research focuses on computational modeling of sentence processing in unimpaired and impaired populations, and the application of mathematical, computational, experimental, and statistical methods (particularly Bayesian methods) in linguistics and psychology. He created an annual summer school, Statistical Methods in Linguistics and Psychology (SMLP), which started in 2017: vasishth.github.io/smlp. He regularly teaches short courses on statistical data analysis (Bayesian and frequentist methods). 

\mainmatter
